name: panvimdoc

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - name: Wait until linting succeeds
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: master
          check-name: Luacheck
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Wait until linting succeeds
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: master
          check-name: StyLua
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Wait until linting succeeds
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: master
          check-name: Readme config
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - uses: actions/checkout@v2

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: toggletasks
          description: Project-local task management

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(ci): auto generate docs"
          branch: ${{ github.head_ref }}
